! DO NOT EDIT THIS FILE!!!
!
! This file is automatically generated by write_probin.py at
! compile-time.
!
! To add a runtime parameter, do so by editting the appropriate _parameters
! file.

! This module stores the runtime parameters.  The probin_init() routine is
! used to initialize the runtime parameters

! this version is a stub -- useful for when we only need a container for 
! parameters, but not for MAESTRO use.

module probin_module

  use amrex_fort_module, only : rt => amrex_real

  implicit none

  private

  integer, save, public :: a_dummy_var = 0

#ifdef CUDA  
#endif

end module probin_module


module extern_probin_module

  use amrex_fort_module, only : rt => amrex_real

  implicit none

  private

  real (kind=rt), save, public :: small_x = 1.d-30
  !$acc declare create(small_x)
  logical, save, public :: use_tables = .false.
  !$acc declare create(use_tables)
  logical, save, public :: use_c12ag_deboer17 = .false.
  !$acc declare create(use_c12ag_deboer17)
  logical, save, public :: use_eos_coulomb = .true.
  !$acc declare create(use_eos_coulomb)
  logical, save, public :: eos_input_is_constant = .false.
  !$acc declare create(eos_input_is_constant)
  real (kind=rt), save, public :: eos_ttol = 1.0d-8
  !$acc declare create(eos_ttol)
  real (kind=rt), save, public :: eos_dtol = 1.0d-8
  !$acc declare create(eos_dtol)

#ifdef CUDA  
#endif

end module extern_probin_module


module runtime_init_module

  use amrex_error_module
  use amrex_fort_module, only : rt => amrex_real
  use probin_module
  use extern_probin_module

  implicit none

  namelist /probin/ small_x
  namelist /probin/ use_tables
  namelist /probin/ use_c12ag_deboer17
  namelist /probin/ use_eos_coulomb
  namelist /probin/ eos_input_is_constant
  namelist /probin/ eos_ttol
  namelist /probin/ eos_dtol

  private

  public :: probin

  public :: runtime_init, runtime_close, runtime_pretty_print

contains

  subroutine runtime_init(read_inputs_in)

    logical, intent(in), optional :: read_inputs_in

    integer :: farg, narg
    character(len=128) :: fname
    logical    :: lexist
    integer :: un

    logical :: read_inputs



    narg = command_argument_count()

    if (.not. present(read_inputs_in)) then
       read_inputs = .false.
    else
       read_inputs = read_inputs_in
    endif

    if (read_inputs) then
       farg = 1
       if ( narg >= 1 ) then
          call get_command_argument(farg, value = fname)
          inquire(file = fname, exist = lexist )
          if ( lexist ) then
             farg = farg + 1
             open(newunit=un, file = fname, status = 'old', action = 'read')
             read(unit=un, nml = probin)
             close(unit=un)
          else
             call amrex_error("ERROR: inputs file does not exist")
          endif
       else
          call amrex_error("ERROR: no inputs file specified")
       endif
    endif

    !$acc update &
    !$acc device(small_x, use_tables, use_c12ag_deboer17) &
    !$acc device(use_eos_coulomb, eos_input_is_constant, eos_ttol) &
    !$acc device(eos_dtol)

  end subroutine runtime_init

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  subroutine runtime_close()

    use probin_module


  end subroutine runtime_close

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  subroutine runtime_pretty_print(unit)

    use amrex_constants_module
    use probin_module
    use extern_probin_module

    integer, intent(in) :: unit

    write (unit, *) "[*] indicates overridden default"

100 format (1x, a3, 2x, a32, 1x, "=", 1x, a)
101 format (1x, a3, 2x, a32, 1x, "=", 1x, i10)
102 format (1x, a3, 2x, a32, 1x, "=", 1x, g20.10)
103 format (1x, a3, 2x, a32, 1x, "=", 1x, l)
    write (unit,102) merge("   ", "[*]", small_x == 1.d-30), &
 "small_x", small_x
    write (unit,103) merge("   ", "[*]", use_tables .eqv. .false.), &
 "use_tables", use_tables
    write (unit,103) merge("   ", "[*]", use_c12ag_deboer17 .eqv. .false.), &
 "use_c12ag_deboer17", use_c12ag_deboer17
    write (unit,103) merge("   ", "[*]", use_eos_coulomb .eqv. .true.), &
 "use_eos_coulomb", use_eos_coulomb
    write (unit,103) merge("   ", "[*]", eos_input_is_constant .eqv. .false.), &
 "eos_input_is_constant", eos_input_is_constant
    write (unit,102) merge("   ", "[*]", eos_ttol == 1.0d-8), &
 "eos_ttol", eos_ttol
    write (unit,102) merge("   ", "[*]", eos_dtol == 1.0d-8), &
 "eos_dtol", eos_dtol

  end subroutine runtime_pretty_print


end module runtime_init_module
