name: ecsn

on: [pull_request]
jobs:
  ecsn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get AMReX
        run: |
          mkdir external
          cd external
          git clone https://github.com/AMReX-Codes/amrex.git
          cd amrex
          git checkout development
          echo 'AMREX_HOME=$(GITHUB_WORKSPACE)/external/amrex' >> $GITHUB_ENV
          echo $AMREX_HOME
          if [[ -n "${AMREX_HOME}" ]]; then exit 1; fi
          cd ../..

      - name: Get Microphysics
        run: |
          cd external
          git clone https://github.com/AMReX-Astro/Microphysics.git
          cd Microphysics
          git checkout development
          echo 'MICROPHYSICS_HOME=$(GITHUB_WORKSPACE)/external/Microphysics' >> $GITHUB_ENV
          echo $MICROPHYSICS_HOME
          if [[ -n "${MICROPHYSICS_HOME}" ]]; then exit 1; fi
          cd ../..

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install curl cmake jq clang g++>=9.3.0

      - name: Compile
        run: |
          cd ECSN
          make -j2

      - name: Run with regular grid
        run: |
          ulimit -s 16384
          cd ECSN
          ./initialmodel1d.gnu.ex inputs

      - name: Compare to stored output
        run: |
          cd ECSN
          diff ECSN-ONe6040-final.hse.dx24414.06cm ci-benchmarks/ECSN-ONe6040-final.hse.dx24414.06cm




